services:
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx:alpine
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./configs/auth:/etc/nginx/auth
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/${SSL_DOMAIN}:/etc/letsencrypt/live/${SSL_DOMAIN}
      - /etc/letsencrypt/archive/${SSL_DOMAIN}:/etc/letsencrypt/archive/${SSL_DOMAIN}
      - ./frontend:/usr/share/nginx/html
    restart: unless-stopped

  database:
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data


  backend:
    container_name: backend
    image: node
    depends_on: 
      - database
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development

volumes:
  db_data: